# Generated by Django 5.2.5 on 2025-08-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0002_seller_sellername_alter_seller_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="sellerName",
            field=models.CharField(max_length=10),
        ),
    ]
