# Generated by Django 4.2.23 on 2025-08-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
