# Generated by Django 5.2.5 on 2025-08-11 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0002_products_delete_recipes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="products",
        ),
    ]
