# Generated by Django 5.2.5 on 2025-08-10 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('cooking_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('cooking_dc', models.CharField(max_length=300)),
                ('step_tip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('recipe_nm_ko', models.CharField(max_length=15)),
                ('sumry', models.CharField(max_length=100)),
                ('nation_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('nation_nm', models.CharField(max_length=10)),
                ('ty_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('ty_nm', models.CharField(max_length=10)),
                ('cooking_time', models.CharField(max_length=10)),
                ('calorie', models.CharField(max_length=10)),
                ('qnt', models.CharField(max_length=10)),
                ('level_nm', models.CharField(max_length=10)),
                ('irdnt_code', models.CharField(max_length=10)),
                ('pc_nm', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='irdnt_sn',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='irdnt_ty_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='recipe_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
