# Generated by Django 5.2.5 on 2025-08-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="sellerName",
            field=models.CharField(
                default="default_seller", max_length=10, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="seller",
            name="password",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="seller",
            name="username",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
