# Generated by Django 5.2.5 on 2025-08-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="username",
            new_name="seller",
        ),
    ]
