# Generated by Django 4.2.23 on 2025-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
