# Generated by Django 4.2.23 on 2025-08-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_itemcode'),
        ('products', '0002_rename_username_products_seller'),
    ]

    operations = [
    ]
