# Generated by Django 5.2.5 on 2025-08-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_merge_20250812_1632"),
        ("products", "0003_merge_20250812_1648"),
    ]

    operations = []
