# Generated by Django 5.2.5 on 2025-08-11 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_products_uploaded_image"),
        ("seller", "0003_alter_seller_sellername"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="username",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="seller.seller",
            ),
            preserve_default=False,
        ),
    ]
