# Generated by Django 4.2.23 on 2025-08-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20250812_1632'),
        ('products', '0004_order_orderitem'),
    ]

    operations = [
    ]
