# Generated by Django 5.2.5 on 2025-08-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_products_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="uploaded_image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
