# Generated by Django 4.2.23 on 2025-08-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
